# Generated by Django 4.2.7 on 2023-12-30 12:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('password', models.CharField(default='123', max_length=128)),
                ('gender', models.CharField(max_length=1)),
                ('sec_question', models.CharField(max_length=50)),
                ('sec_answer', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30, null=True)),
                ('year', models.IntegerField(null=True)),
                ('millage', models.IntegerField(null=True)),
                ('tax', models.IntegerField(null=True)),
                ('mpg', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('engineSize', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('transmission_automatic', models.IntegerField(null=True)),
                ('transmission_manual', models.IntegerField(null=True)),
                ('transmission_semi', models.IntegerField(null=True)),
                ('fuel_diesel', models.IntegerField(null=True)),
                ('fuel_electric', models.IntegerField(null=True)),
                ('fuel_hybrid', models.IntegerField(null=True)),
                ('fuel_other', models.IntegerField(null=True)),
                ('fuel_petrol', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_dependents', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('anual_income', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('loan_ammount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('loan_term', models.IntegerField(null=True)),
                ('cibil_score', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('residental_assets_value', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('commercial_assets_value', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('luxury_assets_value', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('bank_asset_value', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('graduate', models.IntegerField(null=True)),
                ('employed', models.IntegerField(null=True)),
                ('result', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
        migrations.DeleteModel(
            name='Houses',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product_category'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='automobile_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.carmodel'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.loanmodel'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
